name: build-all

on:
  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: '10 2 * * 1'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerimage:
          - alpine-ansible
          - amazon-ansible
          - arch-ansible
          - centos7-ansible
          - centos8-ansible
          - rocky8-ansible
          - debian10-ansible
          - debian9-ansible
          - fedora-ansible
          - opensuse_tumbleweed-ansible
          - openwrt-ansible
          - oracle7-ansible
          - ubuntu1804-ansible
          - ubuntu2004-ansible
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.dockerimage }}-latest
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-${{ matrix.dockerimage }}:test
      -
        name: Test
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/docker-${{ matrix.dockerimage }}:test
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.dockerimage }}-latest
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-${{ matrix.dockerimage }}:latest
      -
        name: (Temporarily Disabled) Update repo description
        run: echo "Do not forget to revert the commit before contributing to upstream!"